name: aks-servicemesh-tf

env:
  path: aks-servicemesh-tf

on:
  push:
    branches:
      - master
    paths:
      - "$GITHUB_WORKFLOW/**"
  pull_request:
  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform testing"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

    - name: Init-Plan-Apply-Destroy
      uses: ams0/terraform-test-in-azure@master
      with:
        arm_client_id: ${{ secrets.ARM_CLIENT_ID }}
        arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
        arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}
        variables: "-var-file=./terraform.tfvarsexample"
        path: ${{ env.path }}/terraform
